# Regenerates scripts/gallery-data.js from assets/images/gallery/.
#
# Folder layout expected:
#   assets/images/gallery/<Category>/<album-name>/cover.<ext>   (+ optional extra photos)
#
# Run this after adding/removing/renaming any folder or photo under assets/images/gallery,
# then commit the updated scripts/gallery-data.js along with your image changes.

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$galleryDir = Join-Path $repoRoot 'assets\images\gallery'
$outFile    = Join-Path $repoRoot 'scripts\gallery-data.js'
$imageExts  = @('.jpg', '.jpeg', '.png', '.webp', '.gif')

# Categories are interleaved round-robin in this order on the "All" view.
# Any category folder not listed here is appended after, alphabetically.
$categoryOrder = @('Crochet', 'Cooking')

function ToTitle($slug) {
    $words = ($slug -replace '[-_]+', ' ').Trim() -split ' '
    ($words | ForEach-Object {
        if ($_.Length -eq 0) { $_ } else { $_.Substring(0,1).ToUpper() + $_.Substring(1) }
    }) -join ' '
}

function ToSlug($name) {
    $s = $name.ToLowerInvariant()
    $s = $s -replace "'", ''
    $s = $s -replace '[^a-z0-9]+', '-'
    $s.Trim('-')
}

function JsString($s) {
    "'" + ($s -replace '\\', '\\\\' -replace "'", "\'") + "'"
}

# Zero-pads embedded numbers so string sort order matches numeric order
# (e.g. "2" sorts before "10").
function NaturalKey($name) {
    [regex]::Replace($name, '\d+', { param($m) $m.Value.PadLeft(10, '0') })
}

$byCategory = [ordered]@{}

if (Test-Path $galleryDir) {
    Get-ChildItem -Path $galleryDir -Directory | Sort-Object { NaturalKey $_.Name } | ForEach-Object {
        $category = $_.Name
        $categoryAlbums = @()

        # Albums are named "<number>-<name>" — higher numbers sort first.
        Get-ChildItem -Path $_.FullName -Directory | Sort-Object { NaturalKey $_.Name } -Descending | ForEach-Object {
            $albumDir  = $_
            $files     = Get-ChildItem -Path $albumDir.FullName -File |
                Where-Object { $imageExts -contains $_.Extension.ToLowerInvariant() }
            $coverFile = $files | Where-Object { $_.BaseName.ToLowerInvariant() -eq 'cover' } | Select-Object -First 1
            if (-not $coverFile) { return }  # skip album folders without a cover image

            $otherFiles = $files | Where-Object { $_.FullName -ne $coverFile.FullName } | Sort-Object { NaturalKey $_.Name }

            $relBase = "assets/images/gallery/$category/$($albumDir.Name)"
            $cover   = "$relBase/$($coverFile.Name)"
            $images  = @($cover) + ($otherFiles | ForEach-Object { "$relBase/$($_.Name)" })

            $categoryAlbums += [PSCustomObject]@{
                id       = "$(ToSlug $category)-$(ToSlug $albumDir.Name)"
                category = $category
                title    = ToTitle $albumDir.Name
                cover    = $cover
                images   = $images
            }
        }

        $byCategory[$category] = $categoryAlbums
    }
}

# Category iteration order: $categoryOrder first, then any leftovers alphabetically.
$orderedCategories = @($categoryOrder | Where-Object { $byCategory.Contains($_) })
$orderedCategories += @($byCategory.Keys | Where-Object { $orderedCategories -notcontains $_ } | Sort-Object { NaturalKey $_ })

# Round-robin merge: one album from each category in turn, cycling until all are used.
$albums = @()
$cursors = @{}
$orderedCategories | ForEach-Object { $cursors[$_] = 0 }
$remaining = $true
while ($remaining) {
    $remaining = $false
    foreach ($category in $orderedCategories) {
        $list = $byCategory[$category]
        $i = $cursors[$category]
        if ($i -lt $list.Count) {
            $albums += $list[$i]
            $cursors[$category] = $i + 1
            if ($i + 1 -lt $list.Count) { $remaining = $true }
        }
    }
}

$lines = @()
$lines += '// AUTO-GENERATED by scripts/build-gallery.ps1 -- do not edit by hand.'
$lines += '// Re-run that script after changing anything under assets/images/gallery.'
$lines += 'const GALLERY = ['
foreach ($a in $albums) {
    $imagesJs = ($a.images | ForEach-Object { JsString $_ }) -join ', '
    $lines += "  { id: $(JsString $a.id), category: $(JsString $a.category), title: $(JsString $a.title), cover: $(JsString $a.cover), images: [$imagesJs] },"
}
$lines += '];'
$lines += ''

Set-Content -Path $outFile -Value ($lines -join "`r`n") -Encoding UTF8

Write-Host "Wrote $($albums.Count) album(s) to $outFile"
