// AUTO-GENERATED by scripts/build-gallery.ps1 -- do not edit by hand.
// Re-run that script after changing anything under assets/images/gallery.
const GALLERY = [
  { id: 'crochet-12-vest', category: 'Crochet', title: '12 Vest', cover: 'assets/images/gallery/Crochet/12-vest/cover.jpg', images: ['assets/images/gallery/Crochet/12-vest/cover.jpg', 'assets/images/gallery/Crochet/12-vest/1.jpg', 'assets/images/gallery/Crochet/12-vest/2.jpg', 'assets/images/gallery/Crochet/12-vest/3.jpg'] },
  { id: 'cooking-5-baking', category: 'Cooking', title: '5 Baking', cover: 'assets/images/gallery/Cooking/5-baking/cover.jpg', images: ['assets/images/gallery/Cooking/5-baking/cover.jpg'] },
  { id: 'crochet-11-bagpack', category: 'Crochet', title: '11 Bagpack', cover: 'assets/images/gallery/Crochet/11-bagpack/cover.jpg', images: ['assets/images/gallery/Crochet/11-bagpack/cover.jpg', 'assets/images/gallery/Crochet/11-bagpack/1.jpg', 'assets/images/gallery/Crochet/11-bagpack/2.jpg', 'assets/images/gallery/Crochet/11-bagpack/3.jpg'] },
  { id: 'cooking-4-family', category: 'Cooking', title: '4 Family', cover: 'assets/images/gallery/Cooking/4-family/cover.jpg', images: ['assets/images/gallery/Cooking/4-family/cover.jpg', 'assets/images/gallery/Cooking/4-family/1.jpg', 'assets/images/gallery/Cooking/4-family/2.jpg'] },
  { id: 'crochet-10-rainbowhat', category: 'Crochet', title: '10 Rainbowhat', cover: 'assets/images/gallery/Crochet/10-rainbowhat/cover.jpg', images: ['assets/images/gallery/Crochet/10-rainbowhat/cover.jpg', 'assets/images/gallery/Crochet/10-rainbowhat/1.jpg', 'assets/images/gallery/Crochet/10-rainbowhat/2.jpg'] },
  { id: 'cooking-3-flour', category: 'Cooking', title: '3 Flour', cover: 'assets/images/gallery/Cooking/3-flour/cover.jpg', images: ['assets/images/gallery/Cooking/3-flour/cover.jpg'] },
  { id: 'crochet-9-small-scarf', category: 'Crochet', title: '9 Small Scarf', cover: 'assets/images/gallery/Crochet/9-small-scarf/cover.jpg', images: ['assets/images/gallery/Crochet/9-small-scarf/cover.jpg'] },
  { id: 'cooking-2-meat', category: 'Cooking', title: '2 Meat', cover: 'assets/images/gallery/Cooking/2-meat/cover.jpg', images: ['assets/images/gallery/Cooking/2-meat/cover.jpg', 'assets/images/gallery/Cooking/2-meat/1.jpg', 'assets/images/gallery/Cooking/2-meat/2.jpg'] },
  { id: 'crochet-8-scarf', category: 'Crochet', title: '8 Scarf', cover: 'assets/images/gallery/Crochet/8-scarf/cover.jpg', images: ['assets/images/gallery/Crochet/8-scarf/cover.jpg'] },
  { id: 'cooking-1-daily', category: 'Cooking', title: '1 Daily', cover: 'assets/images/gallery/Cooking/1-daily/cover.jpg', images: ['assets/images/gallery/Cooking/1-daily/cover.jpg', 'assets/images/gallery/Cooking/1-daily/1.jpg', 'assets/images/gallery/Cooking/1-daily/2.jpg', 'assets/images/gallery/Cooking/1-daily/4.jpg'] },
  { id: 'crochet-7-flower-bag', category: 'Crochet', title: '7 Flower Bag', cover: 'assets/images/gallery/Crochet/7-flower-bag/cover.jpg', images: ['assets/images/gallery/Crochet/7-flower-bag/cover.jpg'] },
  { id: 'crochet-6-flower', category: 'Crochet', title: '6 Flower', cover: 'assets/images/gallery/Crochet/6-flower/cover.jpg', images: ['assets/images/gallery/Crochet/6-flower/cover.jpg'] },
  { id: 'crochet-5-market-bag', category: 'Crochet', title: '5 Market Bag', cover: 'assets/images/gallery/Crochet/5-market-bag/cover.jpg', images: ['assets/images/gallery/Crochet/5-market-bag/cover.jpg'] },
  { id: 'crochet-4-iphone-bag', category: 'Crochet', title: '4 Iphone Bag', cover: 'assets/images/gallery/Crochet/4-iphone-bag/cover.jpg', images: ['assets/images/gallery/Crochet/4-iphone-bag/cover.jpg'] },
  { id: 'crochet-3-adas-hat', category: 'Crochet', title: '3 Adas Hat', cover: 'assets/images/gallery/Crochet/3-adas-hat/cover.jpg', images: ['assets/images/gallery/Crochet/3-adas-hat/cover.jpg'] },
  { id: 'crochet-2-hat', category: 'Crochet', title: '2 Hat', cover: 'assets/images/gallery/Crochet/2-hat/cover.jpg', images: ['assets/images/gallery/Crochet/2-hat/cover.jpg'] },
  { id: 'crochet-1-hat2', category: 'Crochet', title: '1 Hat2', cover: 'assets/images/gallery/Crochet/1-hat2/cover.jpg', images: ['assets/images/gallery/Crochet/1-hat2/cover.jpg'] },
];

